_wandb:
    value:
        cli_version: 0.19.8
        m: []
        python_version: 3.13.2
        t:
            "1":
                - 1
                - 11
                - 49
                - 55
            "2":
                - 1
                - 11
                - 49
                - 55
            "3":
                - 16
                - 23
                - 55
            "4": 3.13.2
            "5": 0.19.8
            "6": 4.49.0
            "8":
                - 3
                - 5
            "12": 0.19.8
            "13": windows-amd64
batch_size:
    value: 64
device:
    value: cuda
dropout_rate:
    value: 0.1
embed_dim:
    value: 512
epochs:
    value: 500
learning_rate:
    value: 1e-05
model_name:
    value: GROUP3-GPT-TRANSFORMER-DEMO
num_heads:
    value: 8
num_layers:
    value: 3
